### ISSUE TITLE
Crash on uninstalling mods

### ISSUE THREAD

**Issue by AdaBallard** [aa2g/AA2Install#10]
I installed the 6.3 version of AA2install, improted mods list from Illusion wizard and installed AA2 HEXA Override Collection v2.8 and  AA2 HEXA Clothing Collection MK-III v5.0 successfully.

But now when I try to uninstall any of them, it crashes on "creating pp queue" saying "Non-negative number is required" (full log text is in txt file).

I tried clearing the cache - no effect. I'm not much a of a programmer so I don't know how to build the latest commit.

Hope you can fix this.

Necessary files:

[AA2Install crash 17-4-2016 05-57-04.zip](https://github.com/aa2g/AA2Install/files/222569/AA2Install.crash.17-4-2016.05-57-04.zip)
[error_text.txt](https://github.com/aa2g/AA2Install/files/222570/error_text.txt)
[config.json.gz](https://github.com/aa2g/AA2Install/files/222571/config.json.gz)

**Comment by AdaBallard** [comment]
[AA2Install crash 17-4-2016 05-57-04.zip](https://github.com/aa2g/AA2Install/files/222565/AA2Install.crash.17-4-2016.05-57-04.zip)
[config.json.gz](https://github.com/aa2g/AA2Install/files/222567/config.json.gz)
[error_text.txt](https://github.com/aa2g/AA2Install/files/222568/error_text.txt)

**Comment by patrickb8man** [comment]
This seems to be an issue with the SB3Utility library AA2Install uses to manipulate the .pp files. Can you launch AA2 without any issues? If not then you have a corrupted install. If it still works though, it's out of my control as I have no control over the library, sorry.

**Comment by AdaBallard** [comment]
I can't run AA2 after installing these two mods, that's why I decided to uninstall them. So it means I'll have to reinstall the game and all mods all over?

**Comment by patrickb8man** [comment]
Seems to be the case. I'm sorry that this happened, but the reason for it is entirely out of my control.

**Comment by AdaBallard** [comment]
Lucky enough I have backups. So does this mean AA2intsaller installed the mods in the wrong way and I better use illusion wizard instead next time?

**Comment by patrickb8man** [comment]
It means that there was probably an internal fault with SB3Utility when it was processing the .pp files. You can switch to wizzard if it works better, but if you want to keep using this you can instead use the installer .exe files that are supplied with HEXACC, although you won't be able to uninstall them.

**Comment by AdaBallard** [comment]
Looks like i found the reason why the bug happens. I checked the console output when installing hexacc and it's saying on extraction of the mod: "Files with Errors: 1". I checked the mod's 7z file with 7zgui's test and it found no errors! 

So maybe the reason is 7z module used with aa2installer extracts files in a wrong way, so no wonder installation gets corrupted after installing these files.

**Comment by AdaBallard** [comment]
So it looks like 7z modules are really the source of the problem, since you were using 15.06 beta. I got v 15.14 from their 7z's github and replaced corresponding dll and exe files in tools\7z\ directory. It works like a charm now, the game runs correctly and installation/uninstallation works  like they should.

The only small problem that still remains is when i try to install "Compatibilities and Buttons by Ogoro" mod, it installs successfully, but remains unchecked and still being shown as uninstalled. Can this be fixed?

**Comment by patrickb8man** [comment]
Yes, I've already rewritten how 7z files are handled in the latest commit and it uses the latest 7z modules (15.14) so the issue with that has already been fixed.

For your last problem, have you looked inside the mod you're trying to install? If the structure of the 7z isn't the same as a wizzard-ready mod then AA2Install will try to install it, find no files to install in the predefined structure and not report as installed as it didn't find any files to install in the first place.

In the latest commit, AA2Install indicates if this is the case and what action needs to be taken about it. If you want, I can build the latest commit for you to try and report if you continue to have issues (taking into consideration that it passes the automatic tests but the actual user tests haven't been run)

**Comment by AdaBallard** [comment]
Well, the structure looks like wizard-ready. Illusion wizard can install and uninstall it with no problems. I dunno if external links are allowed here, so I put it here so you can check it. 
I had to put 7z inside zip though to upload it.

[[AA2][Misc][Compatibilities and Buttons by Ogoro].zip](https://github.com/aa2g/AA2Install/files/223080/AA2.Misc.Compatibilities.and.Buttons.by.Ogoro.zip)

And yes, i would gladly test  the new version of installer. I have a backup of aa2 with no mods, so I'll be able to install all the mods over and check for any issues.

**Comment by patrickb8man** [comment]
External links are fine here. I'm pretty sure the reason why it doesn't like that mod is because of the capitalization of the "AA2_PLAY" folder inside of the mod. Without going into great technical detail as to why the capitalization matters with AA2Install and why it doesn't with Wizzard, fixing up the folder inside the mod should do the trick.

If you want to try the latest commit, I've uploaded a build here: https://mega.nz/#!BkcDUBLR!ghlyMtX-NfibS8yaEmVdovarNalOJ7tuQ0YBXsselnA

I haven't added in the proper folders but it should generate them when you launch the program for the first time.
I'd recommend using it in a completely new folder and not overwrite it with your old AA2Install version. You can copy over the mods and backups folder though.

**Comment by AdaBallard** [comment]
Everything seems to be OK with the new version, the game runs fine, though an "autoscroll log" checkbox in the log tab would be nice, along with "total time spent" lines in the log showing how much time exactly was spent for all synchronization process (possibly).

The ogoro's mod installs fine now and is shown as installed, though it requires to enable "Ignore conflicts" in the options. Without it it stops installation and log shows which files are exactly conflicting, this is really useful feature. But it's OK for it as this mod is a fix for the other mod
(details:http://www.hongfire.com/forum/showthread.php/436836-More-Cumming-Positions-H-Compatibility-New-Buttons-addon)
so it's OK that it overwrites some of the files of the other mod.

So maybe the conflict with other mod was the reason for it not being properly installed on the older version of installer, instead of capitalization problem?

Anyway, your installer is great!

**Comment by patrickb8man** [comment]
I'll look into those new features when I have v7 where I want it to be, and I'll simply just tack them on the end since they're relatively easy to implement.

That's the way I've intended that feature to work. If the user overwrites something and it messes up their install due to conflicting mods and/or their backup files don't work due to overwrites, and they can't push the blame onto me when it warned them that they were running the (albeit very small) risk.

The reason why AA2Install couldn't install it was because due to the way it handles 7z extraction causes it to be strict when it comes to capitalization. Nothing was extracted from the 7z in the first place since it didn't conform to it's strict rules, whilst Wizzard was a bit more lenient. I can look into it since I'm pretty sure it's an easy fix but if this is the first time this issue has occurred in around 6 months of the tool existing I'm not sure if I should go out of my way to do it.

(I'm probably going to do it anyway since I have nothing better to do with my time)
